services:
  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Allocate memory for Elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - es_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - ./backend:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017
      ELASTIC_URI: http://elasticsearch:9200
      PORT: 5000
      jwtSecret: thisisfunprojectsoplzdonthackit
    command: [ "node", "app.js" ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    environment:
      VITE_BACKEND_URL: "http://localhost:5000/"
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: .frontend
          target: /usr/app

volumes:
  node_modules:
  es_data:
    driver: local
